substitutions:
  _REGION: europe-west2
  _REPO: gcp-banking
  _SERVICE: banking-api
  _IMAGE: ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/app:latest


steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', '${_IMAGE}', '.']

  - name: gcr.io/cloud-builders/docker
    args: ['push', '${_IMAGE}']

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args: ['run', 'deploy', '${_SERVICE}',
           '--image', '${_IMAGE}',
           '--region', '${_REGION}',
           '--allow-unauthenticated']

images:
  - ${_IMAGE}

# Send build logs to your GCS bucket (required because a user-managed SA is used)
logsBucket: gs://gcp-banking-platform-cloudbuild-logs
options:
  logging: GCS_ONLY
