steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Deploying Cloud Run service..."
        gcloud run deploy banking-web \
          --source . \
          --region europe-west2 \
          --allow-unauthenticated \
          --service-account 850076514657-compute@developer.gserviceaccount.com \
          --set-env-vars INSTANCE_CONNECTION_NAME=${PROJECT}:${REGION}:banking-sql

substitutions:
  _REGION: europe-west2
  _SERVICE: banking-web
  _INSTANCE: banking-sql
  _SA_EMAIL: 850076514657-compute@developer.gserviceaccount.com
