steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        echo "Deploying Cloud Run service..."
        REGION="europe-west2"
        SERVICE="banking-web"
        INSTANCE="banking-sql"
        SA="850076514657-compute@developer.gserviceaccount.com"
        CONN=$(gcloud sql instances describe "$INSTANCE" --format='value(connectionName)')
        gcloud run deploy "$SERVICE" \
          --source . \
          --region "$REGION" \
          --allow-unauthenticated \
          --service-account "$SA" \
          --add-cloudsql-instances "$CONN" \
          --set-env-vars "DB_HOST=/cloudsql/$CONN"

options:
  logging: CLOUD_LOGGING_ONLY
